CREATE TABLE IF NOT EXISTS guild_security (
  guild_id TEXT PRIMARY KEY,
  antiNukeEnabled INTEGER NOT NULL DEFAULT 1,
  antiRaidEnabled INTEGER NOT NULL DEFAULT 1,
  autoModEnabled INTEGER NOT NULL DEFAULT 1,
  antiSpamEnabled INTEGER NOT NULL DEFAULT 1,
  antiNukeChannelDelete INTEGER NOT NULL DEFAULT 3,
  antiNukeRoleDelete INTEGER NOT NULL DEFAULT 3,
  antiNukeBan INTEGER NOT NULL DEFAULT 5,
  antiNukeKick INTEGER NOT NULL DEFAULT 5,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
